service:
  name: sansan

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  memorySize: 128
  timeout: 30
#  iamRoleStatements:
#  - Effect: Allow
#    Action:
#    - dynamodb:*
#    Resource:
#    - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"
#  - Effect: Allow
#    Action:
#    - s3:*
#    Resource:
#    - "arn:aws:s3:::tegaki-image/*"

functions:
  getCards:
    handler: handler.getCards
    events:
    - http:
        method: get
        path: card/index
        cors: false